version: '3'

services:
  mongo:
    image: mongo:6.0
    container_name: poc_mock_mongo
    environment:
      MONGO_INITDB_DATABASE: mocks
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network: